apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    product: sagl
    app: server-api
  name: server-api
  namespace: xeonr-prod-sagl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        product: sagl
        app: server-api
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault-active.vault.svc.cluster.local:8200
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/vault-path: kubernetes
        vault.security.banzaicloud.io/vault-role: sagl-prod-server-api
        vault.security.banzaicloud.io/enable-json: "true"
      name: server-api
    spec:
      serviceAccountName: vault-auth
      containers:
        - image: europe-west1-docker.pkg.dev/xeonr-io/sagl/server-api
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: production
            - name: MONGODB_URI
              value: "vault:sagl/data/database/mongodb#uri"
            - name: CLICKHOUSE_HOST
              value: "vault:sagl/data/database/clickhouse#host"
            - name: CLICKHOUSE_USERNAME
              value: "vault:sagl/data/database/clickhouse#username"
            - name: CLICKHOUSE_PASSWORD
              value: "vault:sagl/data/database/clickhouse#password"
            - name: CLICKHOUSE_DATABASE
              value: "vault:sagl/data/database/clickhouse#database"
            - name: AWS_ACCESS_KEY_ID
              value: "vault:sagl/data/server-api/s3#accessKeyId"
            - name: AWS_SECRET_ACCESS_KEY
              value: "vault:sagl/data/server-api/s3#secretAccessKey"
            - name: S3_SERVER_BUCKET
              value: "vault:sagl/data/server-api/s3#bucket"
            - name: JWT_TOKEN
              value: "vault:sagl/data/server-api/jwt#cloudApiSecret"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
          name: server-api
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: server-api
  name: server-api
  namespace: xeonr-prod-sagl
spec:
  type: ClusterIP
  selector:
    app: server-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: server-api
  namespace: xeonr-prod-sagl
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`server-api.sagl.app`)
      priority: 10
      services:
        - name: server-api
          port: 80
    - kind: Rule
      match: Host(`api.sagl.mp`)
      priority: 11
      services:
        - name: server-api
          port: 80
