on:
  push:
    branches:
    - main

name: Build and Deploy SAGL Server API
env:
  REGION: europe-west1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: xeonr-io
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build and Push Container
      run: |-
        docker build --build-arg MAXMIND_APIKEY=${{secrets.MAXMIND_APIKEY}} --build-arg NPM_TOKEN=${{secrets.GH_SECRET}} -t europe-west1-docker.pkg.dev/xeonr-io/sagl/server-api:${{  github.run_number }} .
        docker push europe-west1-docker.pkg.dev/xeonr-io/sagl/server-api:${{  github.run_number }}

    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: "${{ secrets.PROD_KUBECONFIG }}"

    - uses: Azure/k8s-deploy@v3.1
      with:
        namespace: "xeonr-prod-sagl"
        imagepullsecrets: gcr-docker
        strategy: none
        manifests: |
          infra/production.yml
        images: "europe-west1-docker.pkg.dev/xeonr-io/sagl/server-api:${{  github.run_number }}"

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '🚀 ${{github.actor}} successfully deployed the SA:GL Server API (Release `${{  github.run_number }}`).'
